---
- name: Restart mysql
  ansible.builtin.service:
    name: "{{ mysql_service_name }}"
    state: restarted

- name: Reload mysql
  ansible.builtin.service:
    name: "{{ mysql_service_name }}"
    state: reloaded
