---
# fake-gcs-server scenario - GCP Cloud Storage emulator
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: gcs-test-instance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    privileged: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    networks:
      - name: gcs-network

  - name: fake-gcs
    image: fsouza/fake-gcs-server:latest
    pre_build_image: true
    command: "-scheme http -public-host fake-gcs:4443"
    exposed_ports:
      - 4443/tcp
    networks:
      - name: gcs-network

provisioner:
  name: ansible
  env:
    ANSIBLE_ALLOW_BROKEN_CONDITIONALS: "true"
    STORAGE_EMULATOR_HOST: "http://fake-gcs:4443"
  inventory:
    hosts:
      all:
        hosts:
          gcs-test-instance:
            ansible_connection: docker
            gcs_endpoint: "http://fake-gcs:4443"

verifier:
  name: ansible
