---
- name: Create consul group
  ansible.builtin.group:
    name: "{{ consul_group }}"
    system: true
    state: present

- name: Create consul user
  ansible.builtin.user:
    name: "{{ consul_user }}"
    group: "{{ consul_group }}"
    system: true
    shell: /usr/sbin/nologin
    home: "{{ consul_data_dir }}"
    create_home: false

- name: Create consul directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: '0750'
  loop:
    - "{{ consul_config_dir }}"
    - "{{ consul_data_dir }}"
    - "{{ consul_log_dir }}"

- name: Download consul binary
  ansible.builtin.get_url:
    url: "https://releases.hashicorp.com/consul/{{ consul_version }}/consul_{{ consul_version }}_linux_amd64.zip"
    dest: /tmp/consul.zip
    mode: '0644'
  register: consul_download

- name: Install unzip
  ansible.builtin.package:
    name: unzip
    state: present

- name: Extract consul binary
  ansible.builtin.unarchive:
    src: /tmp/consul.zip
    dest: /usr/local/bin
    remote_src: true
    mode: '0755'
  when: consul_download.changed

- name: Create consul config
  ansible.builtin.template:
    src: consul.hcl.j2
    dest: "{{ consul_config_dir }}/consul.hcl"
    owner: "{{ consul_user }}"
    group: "{{ consul_group }}"
    mode: '0640'
  notify: Restart consul

- name: Create consul systemd service
  ansible.builtin.template:
    src: consul.service.j2
    dest: /etc/systemd/system/consul.service
    mode: '0644'
  notify:
    - Reload systemd
    - Restart consul

- name: Start and enable consul
  ansible.builtin.service:
    name: consul
    state: started
    enabled: true
