---
galaxy_info:
  role_name: users
  namespace: ansible_molecule
  author: Ansible Molecule Testing Framework
  description: User and group management
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - users
    - groups
    - ssh
    - sudo

dependencies: []
