---
- name: Create minio group
  ansible.builtin.group:
    name: "{{ minio_group }}"
    system: true
    state: present

- name: Create minio user
  ansible.builtin.user:
    name: "{{ minio_user }}"
    group: "{{ minio_group }}"
    system: true
    shell: /usr/sbin/nologin
    home: "{{ minio_data_dir }}"
    create_home: false

- name: Create minio directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
    mode: '0755'
  loop:
    - "{{ minio_install_dir }}"
    - "{{ minio_data_dir }}"

- name: Download minio binary
  ansible.builtin.get_url:
    url: "https://dl.min.io/server/minio/release/linux-amd64/minio"
    dest: "{{ minio_install_dir }}/minio"
    mode: '0755'
    owner: "{{ minio_user }}"
    group: "{{ minio_group }}"
  register: minio_download
  retries: 3
  delay: 5
  until: minio_download is succeeded

- name: Create symlink for minio binary
  ansible.builtin.file:
    src: "{{ minio_install_dir }}/minio"
    dest: /usr/local/bin/minio
    state: link

- name: Create minio environment file
  ansible.builtin.template:
    src: minio.env.j2
    dest: /etc/default/minio
    owner: root
    group: "{{ minio_group }}"
    mode: '0640'
  notify: Restart minio

- name: Create minio systemd service
  ansible.builtin.template:
    src: minio.service.j2
    dest: /etc/systemd/system/minio.service
    mode: '0644'
  notify:
    - Reload systemd
    - Restart minio

- name: Start and enable minio
  ansible.builtin.service:
    name: minio
    state: "{{ minio_service_state }}"
    enabled: "{{ minio_service_enabled }}"

- name: Create buckets (if minio client available)
  ansible.builtin.debug:
    msg: "Bucket creation requires MinIO client (mc). Buckets to create: {{ minio_buckets | map(attribute='name') | list }}"
  when: minio_buckets | length > 0
