---
galaxy_info:
  role_name: packages
  namespace: common
  author: "Your Name"
  description: "Manages package installation and repository configuration"
  company: ""
  license: "MIT"
  min_ansible_version: "2.10"

  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - "8"
        - "9"

  galaxy_tags:
    - packages
    - system
    - apt
    - yum
    - dnf
    - repository

dependencies: []
