---
galaxy_info:
  role_name: s3
  namespace: molecule_test
  author: Ansible Testing
  description: S3-compatible storage simulation using MinIO
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions: ["22.04"]
    - name: Debian
      versions: ["12"]
    - name: EL
      versions: ["9"]
dependencies: []
