---
galaxy_info:
  role_name: redis
  namespace: molecule_test
  author: Ansible Testing
  description: Install and configure Redis cache server
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions: ["22.04"]
    - name: Debian
      versions: ["12"]
    - name: EL
      versions: ["9"]
dependencies: []
