---
# Debian/Ubuntu variables
mysql_package_name: "{% if mysql_use_mariadb %}mariadb-server{% else %}mysql-server{% endif %}"
mysql_service_name: "{% if mysql_use_mariadb %}mariadb{% else %}mysql{% endif %}"
mysql_python_package: python3-pymysql
mysql_config_file: "/etc/mysql/mariadb.conf.d/50-server.cnf"
mysql_socket: "/var/run/mysqld/mysqld.sock"
