---
# Role metadata

galaxy_info:
  role_name: podman
  namespace: containers
  author: Your Name
  description: Install and configure Podman container engine
  company: Your Company

  license: MIT

  min_ansible_version: "2.10"

  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Fedora
      versions:
        - "38"
        - "39"
        - "40"

  galaxy_tags:
    - podman
    - containers
    - docker
    - oci
    - rootless
    - devops

dependencies: []
