---
galaxy_info:
  author: Ansible Molecule Testing
  role_name: consul
  namespace: cloud
  description: Deploy HashiCorp Consul for service discovery
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - focal
    - name: Debian
      versions:
        - bullseye
        - bookworm

dependencies: []
