---
galaxy_info:
  author: Ansible Molecule Testing
  description: IIS Web Server installation and configuration for Windows
  company: Testing Framework
  license: MIT
  min_ansible_version: "2.12"
  role_name: iis
  namespace: windows
  platforms:
    - name: Windows
      versions:
        - "2019"
        - "2022"
  galaxy_tags:
    - windows
    - iis
    - webserver
    - microsoft

dependencies: []


# Note: This role requires a Windows host for molecule testing
# Windows containers can only run on Windows hosts
# For testing on non-Windows hosts, use delegated driver with Windows VMs
