---
consul_version: "1.17.1"
consul_user: consul
consul_group: consul

consul_config_dir: /etc/consul.d
consul_data_dir: /opt/consul/data
consul_log_dir: /var/log/consul

# Server or client mode
consul_server: true
consul_bootstrap_expect: 1
consul_datacenter: dc1
consul_domain: consul

# Addresses
consul_bind_addr: "0.0.0.0"
consul_client_addr: "0.0.0.0"
consul_http_port: 8500
consul_dns_port: 8600

# UI
consul_ui: true

# TLS
consul_tls_enabled: false
