---
galaxy_info:
  role_name: storage_account
  namespace: molecule_test
  author: Ansible Testing
  description: Azure Storage Account simulation using Azurite
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions: ["22.04"]
    - name: Debian
      versions: ["12"]
dependencies: []
