---
# HashiCorp Consul scenario - Service discovery and configuration
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: consul-test-instance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    privileged: true
    command: /sbin/init
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    networks:
      - name: consul-network

  - name: consul
    image: hashicorp/consul:latest
    pre_build_image: true
    command: "agent -dev -client=0.0.0.0"
    exposed_ports:
      - 8500/tcp
      - 8600/tcp
    networks:
      - name: consul-network

provisioner:
  name: ansible
  env:
    ANSIBLE_ALLOW_BROKEN_CONDITIONALS: "true"
  inventory:
    hosts:
      all:
        hosts:
          consul-test-instance:
            ansible_connection: docker
            consul_addr: "http://consul:8500"

verifier:
  name: ansible
