---
# Role metadata

galaxy_info:
  role_name: haproxy
  namespace: molecule_framework
  author: Ansible Molecule Framework
  description: HAProxy load balancer role
  company: Example Corp
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - focal
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - web
    - haproxy
    - loadbalancer
    - proxy

dependencies: []
