---
galaxy_info:
  role_name: alertmanager
  namespace: ansible_molecule
  author: Ansible Molecule Testing Framework
  description: Install and configure Prometheus Alertmanager
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - monitoring
    - prometheus
    - alertmanager
    - alerting

dependencies: []
