---
# Debian/Ubuntu specific variables

base_ntp_package: chrony
base_ntp_service: chrony
base_ntp_config_path: /etc/chrony/chrony.conf
base_ntp_config_template: chrony.conf.j2

base_ssh_service: ssh

base_packages:
  - vim
  - curl
  - wget
  - tar
  - gzip
  - unzip
  - sudo
  - ca-certificates
  - apt-transport-https
  - gnupg2
  - software-properties-common
